from LinearRegression import LinearRegression
import numpy as np

trainingData = np.loadtxt('trainData', dtype=np.float64)
testData = np.loadtxt('testData', dtype=np.float64)

print("For Linear Regression without weight decay")
agent1 = LinearRegression(trainingData, testData, 0)
Ein1, Eout1, w1 = agent1.train(False)
print("Ein error : ", end="")
print(Ein1, end=" ")
print("Eout error : ", end="")
print(Eout1)
print("-------------------")


print("For Linear Regression with weight decay (k = -3)")
agent2 = LinearRegression(trainingData, testData, -3)
Ein2, Eout2, w = agent2.train(True)
print("Ein error : ", end="")
print(Ein2, end=" ")
print("Eout error : ", end="")
print(Eout2)
print("-------------------")


print("For Linear Regression with weight decay (k = 3)")
agent3 = LinearRegression(trainingData, testData, 3)
Ein3, Eout3, w = agent3.train(True)
print("Ein error : ", end="")
print(Ein3, end=" ")
print("Eout error : ", end="")
print(Eout3)
print("-------------------")

print("For Linear Regression with weight decay (k = 2)")
agent4 = LinearRegression(trainingData, testData, 2)
Ein4, Eout4, w = agent4.train(True)
print("Ein error : ", end="")
print(Ein4, end=" ")
print("Eout error : ", end="")
print(Eout4)
print("-------------------")

print("For Linear Regression with weight decay (k = 1)")
agent5 = LinearRegression(trainingData, testData, 1)
Ein5, Eout5, w = agent5.train(True)
print("Ein error : ", end="")
print(Ein5, end=" ")
print("Eout error : ", end="")
print(Eout5)
print("-------------------")

print("For Linear Regression with weight decay (k = 0)")
agent6 = LinearRegression(trainingData, testData, 0)
Ein6, Eout6, w = agent6.train(True)
print("Ein error : ", end="")
print(Ein6, end=" ")
print("Eout error : ", end="")
print(Eout6)
print("-------------------")

print("For Linear Regression with weight decay (k = -1)")
agent7 = LinearRegression(trainingData, testData, -1)
Ein7, Eout7, w = agent7.train(True)
print("Ein error : ", end="")
print(Ein7, end=" ")
print("Eout error : ", end="")
print(Eout7)
print("-------------------")

print("For Linear Regression with weight decay (k = -2)")
agent8 = LinearRegression(trainingData, testData, -2)
Ein8, Eout8, w = agent8.train(True)
print("Ein error : ", end="")
print(Ein8, end=" ")
print("Eout error : ", end="")
print(Eout8)
print("-------------------")